/**
 *	@const Framework
 *	@description autogenerated with build script, holds current verison info
 *	@property {string} version - the version 
 *	@property {string} build - the  build number
 *	@property {string} date - the date of the build
 */
// DO NOT EDIT. Updated from version.json
var Framework = {"version":"4","build":198,"date":"2019-01-17T19:52:04.003Z"}