/**
 *	@const Framework
 *	@description autogenerated with build script, holds current verison info
 *	@property {string} version - the version 
 *	@property {string} build - the  build number
 *	@property {string} date - the date of the build
 */
// DO NOT EDIT. Updated from version.json
var Framework = {"version":"4","build":181,"date":"2017-12-12T00:53:15.939Z"}